export const PLAYER_PLAY = 'PLAYER_PLAY'

export const PLAYER_STOP = 'PLAYER_STOP'

export const PLAYER_CHANGE_VOLUME_LEFT = 'PLAYER_CHANGE_VOLUME_LEFT'

export const PLAYER_CHANGE_VOLUME_RIGHT = 'PLAYER_CHANGE_VOLUME_RIGHT'

export const PLAYER_CHANGE_TIMESHIFT = 'PLAYER_CHANGE_TIMESHIFT'

export const PLAYER_CHANGE_REVERB_VOLUME_LEFT = 'PLAYER_CHANGE_REVERB_VOLUME_LEFT'

export const PLAYER_CHANGE_REVERB_VOLUME_RIGHT = 'PLAYER_CHANGE_REVERB_VOLUME_RIGHT'

export const PLAYER_CHANGE_REVERB_MODE_LEFT = 'PLAYER_CHANGE_REVERB_MODE_LEFT'

export const PLAYER_CHANGE_REVERB_MODE_RIGHT = 'PLAYER_CHANGE_REVERB_MODE_RIGHT'

export const PLAYER_DOWNLOAD_SOUND = 'PLAYER_DOWNLOAD_SOUND'